name: "Tests"

on:
  push:
    paths:
      - '**.hs'
      - '**.nix'
      - 'nix/sources.json'
      - 'ardana-dollar.cabal'
    branches:
      - main
      - staging
  pull_request:
    paths:
      - '**.hs'
      - '**.nix'
      - 'nix/sources.json'
      - 'ardana-dollar.cabal'

jobs:
  check-formatting:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2.3.4

      - run: nix-shell -p haskellPackages.fourmolu --command "./.github/check_formatting.sh"

  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2.3.4

      - run: nix-shell -p haskellPackages.hlint --command "hlint $(git ls-tree -r HEAD --full-tree --name-only | grep -E '.*\.hs')"
        name: Run hlint

  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Build the full CI
        run: nix-build ./nix/ci.nix
