name: "Tests"

on:
  push:
    paths:
      - '**.hs'
      - '**.nix'
      - 'nix/sources.json'
      - 'ardana-dollar.cabal'
    branches:
      - main
      - staging
  pull_request:
    paths:
      - '**.hs'
      - '**.nix'
      - 'nix/sources.json'
      - 'ardana-dollar.cabal'

jobs:
  check-formatting:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2.3.4

      - run: ./.github/check_formatting.sh

  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2.3.4

      - run: hlint $(git ls-tree -r HEAD --full-tree --name-only | grep -E '.*\.hs')
        name: Run hlint

  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2.3.4

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build the full CI on main
        run: nix build .#check.x86_64-linux

      - if: ${{ github.ref == 'refs/heads/staging' }}
        name: Build the full CI on staging
        run: nix build .#check.x86_64-linux

      - if: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/staging' }}
        name: Build the full CI on PR
        run: nix build .#check.x86_64-linux
